networks:
  default:
    driver: bridge

########################### SERVICES
services:
  uptime-kuma:
    restart: unless-stopped
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - '$DATADIR/uptime-kuma:/app/data'
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.16-alpine@sha256:f111cca721507faa0a57e1ffc75210d64c9a9ca0f8375e0336a2a9a88ae2987c
