networks:
  default:
    name: teslamate_net
    driver: bridge

volumes:
  teslamate-grafana-data:
  teslamate-db:

########################### SERVICES
services:
  teslamate:
    restart: unless-stopped
    container_name: teslamate
    image: teslamate/teslamate:3.1.0@sha256:b7b8b21869d789d043f62b404dd689f55c601ef7d02222e92c0f5d596d0b1044
    ports:
      - 127.0.0.1:4000:4000
    environment:
      ENCRYPTION_KEY: $TESLAMATE_ENCRYPTION_KEY
      DATABASE_USER: $TESLAMATE_DB_USER
      DATABASE_PASS: $TESLAMATE_DB_PASS
      DATABASE_NAME: $TESLAMATE_DB_NAME
      DATABASE_HOST: teslamate_database
      MQTT_USERNAME: $TESLAMATE_MQTT_USERNAME
      MQTT_PASSWORD: $TESLAMATE_MQTT_PASSWORD
      MQTT_HOST: host.containers.internal
      TZ: $TZ
      TIME_ZONE: $TZ
    cap_drop:
      - all

  teslamate_grafana:
    restart: unless-stopped
    container_name: teslamate-grafana
    image: teslamate/grafana:3.1.0@sha256:8d7287f44b1eefb39e649175aa14615df648c04a3162da9461d07c8a9ea1c7e9
    ports:
      - 127.0.0.1:4001:3000
    environment:
      DATABASE_USER: $TESLAMATE_DB_USER
      DATABASE_PASS: $TESLAMATE_DB_PASS
      DATABASE_NAME: $TESLAMATE_DB_NAME
      DATABASE_HOST: teslamate_database
      TZ: $TZ
      TIME_ZONE: $TZ
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - ~/code/Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - ~/code/Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards

  teslamate_database:
    restart: unless-stopped
    container_name: teslamate-database
    image: postgres:18.4@sha256:1a5b3e745bbd82d6deb146505e504da3c2f248cac15e431951b148fbe4f8613a
    environment:
      POSTGRES_USER: $TESLAMATE_DB_USER
      POSTGRES_PASSWORD: $TESLAMATE_DB_PASS
      POSTGRES_DB: $TESLAMATE_DB_NAME
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      TIME_ZONE: $TZ
    volumes:
      - teslamate-db:/var/lib/postgresql
