# https://pre-commit.com/hooks.html
exclude: '\.lock$|pnpm-lock\.ya?ml$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: f048515c9a98d7e2e4b034ec77641acc8a58098d
    hooks:
      - id: nixpkgs-fmt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint
  - repo: https://github.com/hija/clean-dotenv
    rev: v0.0.7
    hooks:
      - id: clean-dotenv
  - repo: https://github.com/fidgetingbits/pre-commit-statix
    rev: v1.0.0
    hooks:
      - id: statix-check
  # - repo: local
  #   hooks:
  #     - id: nix fmt
  #       name: Nix fmt
  #       entry: nix fmt
  #       files: \.nix$
  #       language: system
