networks:
  default:
    driver: bridge

services:
  grimmory:
    image: ghcr.io/grimmory-tools/grimmory:v3.2.4@sha256:dfa7afdfcf25d649fd664497a62385dd00cd9678c37546e182c172e41c8e80cb
    container_name: grimmory
    environment:
      - USER_ID=${APP_USER_ID}
      - GROUP_ID=${APP_GROUP_ID}
      - TZ=${TZ}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - BOOKLORE_PORT=${BOOKLORE_PORT}
    depends_on:
      grimmory-mariadb:
        condition: service_healthy
    ports:
      - '${BOOKLORE_PORT}:${BOOKLORE_PORT}'
    volumes:
      - $DATADIR/booklore/data:/app/data
      - $DATADIR/booklore/books:/books
      - $DATADIR/booklore/bookdrop:/bookdrop
    restart: unless-stopped

  grimmory-mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.12@sha256:01635e796763aa14466ac54e72d3ea79efda5d4f160f1f5cf527fc70ffa555ef
    container_name: grimmory-mariadb
    environment:
      - PUID=${DB_USER_ID}
      - PGID=${DB_GROUP_ID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - $DATADIR/booklore/mariadb/config:/config
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10
