networks:
  default:
    driver: bridge

volumes:
  immich-model-cache:

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.139.4@sha256:c3c5eeafa5549e446b5fd71394399178d9c87da1dec5fd9e9a80a5a0f13e9fad
    restart: unless-stopped
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      IMMICH_WORKERS_INCLUDE: 'api'
    volumes:
      - $UPLOAD_LOCATION:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 127.0.0.1:2342:2283
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false

  immich-microservices:
    restart: unless-stopped
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      IMMICH_WORKERS_EXCLUDE: 'api'
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.139.4@sha256:c3c5eeafa5549e446b5fd71394399178d9c87da1dec5fd9e9a80a5a0f13e9fad
    volumes:
      - $UPLOAD_LOCATION:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.139.4@sha256:7eb755fd9989f8554ed8f5332b931caf996826c51498400534c8c78d1c2f226f
    restart: unless-stopped
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
    volumes:
      - immich-model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    restart: unless-stopped
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: $TZ
      TIME_ZONE: $TZ
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
