x-common-app-config: &common-app-config
  restart: unless-stopped
  environment:
    TZ: $TZ
    TIME_ZONE: $TZ

networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homeassistant:
    <<: *common-app-config
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.5.1@sha256:d4fbec16196d5c8bedf32647f0ca7165f654d92a2e81f35a373508d3226cb867
    network_mode: host
    volumes:
      - $DATADIR/homeassistant:/config

  music-assistant-server:
    <<: *common-app-config
    image: ghcr.io/music-assistant/server:2.9.0b9@sha256:4afbfa7313d9d444d82fce0aa04e2780b86ba6079a5c8b6a07801d8467a285f5
    container_name: music-assistant-server
    network_mode: host
    volumes:
      - '$DATADIR/music-assistant/data:/data'
      - '$DATADIR/music-assistant/media:/media'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined

  zigbee2mqtt:
    <<: *common-app-config
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.9.2@sha256:2a21bbf7a664a149024bbe1f776e3151f28ed9db15948270dcbffb89544a41f0
    network_mode: host
    volumes:
      - '$DATADIR/zigbee2mqtt/data:/app/data'
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
    group_add:
      - keep-groups

  zwavejs2mqtt:
    <<: *common-app-config
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:11.16.2@sha256:338fb81ba369ed04edf1a52bedecf486d213c299b9676b11c25b7dca228e9a15
    network_mode: host
    volumes:
      - '$DATADIR/zwavejs2mqtt/store:/usr/src/app/store'
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0
    group_add:
      - keep-groups
    tty: true
    stop_signal: SIGINT
