x-common-app-config: &common-app-config
  restart: unless-stopped
  environment:
    TZ: $TZ
    TIME_ZONE: $TZ

networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homeassistant:
    <<: *common-app-config
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.5.1@sha256:249d5c20ae2ab973bc2ca54c05764e67e2230f14ac5ca5a7d45e228efbb62e67
    network_mode: host
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - $DATADIR/homeassistant:/config

  zigbee2mqtt:
    <<: *common-app-config
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.3.0@sha256:42de8c55dc578a8404a18c43aeb2b7c75be7988179abe9a8195d99a9e7ebb917
    network_mode: host
    ports:
      - 127.0.0.1:8089:8089
    volumes:
      - '$DATADIR/zigbee2mqtt/data:/app/data'
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
    group_add:
      - keep-groups

  zwavejs2mqtt:
    <<: *common-app-config
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:10.4.1@sha256:8338747f963d3ab099a75413ae145038b700b899701289b1bc5a23986f70505d
    network_mode: host
    volumes:
      - '$DATADIR/zwavejs2mqtt/store:/usr/src/app/store'
    ports:
      - 127.0.0.1:3000:3000 # Home Assistant web socket integration
      - 127.0.0.1:8091:8091
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0
    group_add:
      - keep-groups
    tty: true
    stop_signal: SIGINT
