x-common-app-config: &common-app-config
  restart: unless-stopped
  environment:
    TZ: $TZ
    TIME_ZONE: $TZ

networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homeassistant:
    <<: *common-app-config
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.6.3@sha256:aed891b8f801072302815b4b0fab5adb714182967e9d2e2d4a2be558241c73ad
    network_mode: host
    volumes:
      - $DATADIR/homeassistant:/config

  music-assistant-server:
    <<: *common-app-config
    image: ghcr.io/music-assistant/server:2.9.1@sha256:d2fc378b591c83943025df64d7d5bfa722075f02a67e71fc157bed893a5fed6e
    container_name: music-assistant-server
    network_mode: host
    volumes:
      - '$DATADIR/music-assistant/data:/data'
      - '$DATADIR/music-assistant/media:/media'
      - '$DATADIR/music-assistant/cache:/cache'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined

  zigbee2mqtt:
    <<: *common-app-config
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.10.1@sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80
    network_mode: host
    volumes:
      - '$DATADIR/zigbee2mqtt/data:/app/data'
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
    group_add:
      - keep-groups

  zwavejs2mqtt:
    <<: *common-app-config
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:11.19.0@sha256:a4eae18847fe88c07da5b0898c9d983b283c8a8bab712bdf33cbc0cfd67e8b34
    network_mode: host
    volumes:
      - '$DATADIR/zwavejs2mqtt/store:/usr/src/app/store'
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0
    group_add:
      - keep-groups
    tty: true
    stop_signal: SIGINT
