networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homarr:
    restart: unless-stopped
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:v1.68.1@sha256:3d445a96b1d60282e7dfa22b7700df7d049d2f4c061a9520edce9b20d980d66c
    ports:
      - 127.0.0.1:7575:7575
    volumes:
      - $DATADIR/homarr/appdata:/appdata
    environment:
      - TZ=$TZ
      - TIME_ZONE=$TZ
      - SECRET_ENCRYPTION_KEY=$SECRET_ENCRYPTION_KEY
