keys:
  - &odin age1u4eccmyzd6h760mzu2ffyzzc7qpgr2jxh6jwz3lxqtz8wjrhvc0qnh8urv
  - &delling age1s95e33f30k7v4hzdz0vzranetxykhyc53m4knuguxcd5p4xr7usqumjj4y

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *odin
          - *delling
