# keys https://github.com/rvaiya/keyd/blob/2338f11b1ddd81eaddd957de720a3b4279222da0/t/keys.py#L18
# force terminate: <backspace>+<escape>+<enter>
# nix shell nixpkgs#keyd
# sudo keyd monitor
# To setup: sudo ln -s ~/.dotfiles/keyd/default.conf /etc/keyd/default.conf
# sudo systemctl enable keyd --now

[ids]
 # Work Lenovo Wireless Go
17ef:6116

# Laptop internal keyboard
0001:0001

[global]
chord_timeout = 50


[main]
compose = noop

# Home-row modifiers
a = lettermod(meta, a, 150, 200)
s = lettermod(alt, s, 150, 200)
d = lettermod(shift, d, 150, 200)
f = lettermod(control, f, 150, 200)
j = lettermod(control, j, 150, 200)
k = lettermod(shift, k, 150, 200)
l = lettermod(alt, l, 150, 200)
; = lettermod(meta, ;, 150, 200)

# Copy / Paste shorthands
c = timeout(c, 200, C-insert)
v = timeout(v, 200, S-insert)
x = timeout(x, 200, C-x)

# Tap/hold
esc = timeout(esc, 200, f12)
capslock = tab
# rightalt = overloadt(navigation, rightalt, 200)

# Chords
# \
e+f = =

# /
j+i = S-7

# |
j+u = `

# ;
comma+dot = S-,

# =
u+i = S-0

# -
j+k = /

# _
m+comma = S-/

# ~
# j+l = macro(A-] space)

# e+r = (
# r+t = )

# [
d+f = rightalt-8

# ]
f+g = rightalt-9
# c+v = {
# v+b = }
# f+r =
# t+g = >

[navigation]
i = up
j = left
k = down
l = right
u = home
o = end
y = pgup
h = pgdown
m = C-S-tab
. = C-tab

p = print
t = mute
x = previoussong
c = playpause
v = nextsong
