networks:
  default:
    driver: bridge

########################### SERVICES
services:
  valheim:
    image: lloesche/valheim-server@sha256:8f1c5fc831c900312b4a47c1fe57bfc03b574c1433ea502f5d8f0ad301a22a83
    container_name: valheim
    cap_add:
      - sys_nice
    volumes:
      - $DATADIR/valheim/config:/config
      - $DATADIR/valheim/data:/opt/valheim
    ports:
      - '2456:2456/udp'
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      SERVER_NAME: $VALHEIM_SERVER_NAME
      WORLD_NAME: $VALHEIM_WORLD_NAME
      SERVER_PASS: $VALHEIM_SERVER_PASS
      SERVER_PUBLIC: false
    stop_grace_period: 2m
