networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homarr:
    restart: unless-stopped
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:v1.71.0@sha256:ae875bfbcfd6d5cb5d9f40ba656920373c058d73ca3f360d2ffea835c7b76fa9
    ports:
      - 127.0.0.1:7575:7575
    volumes:
      - $DATADIR/homarr/appdata:/appdata
    environment:
      - TZ=$TZ
      - TIME_ZONE=$TZ
      - SECRET_ENCRYPTION_KEY=$SECRET_ENCRYPTION_KEY
