x-common-app-config: &common-app-config
  restart: unless-stopped

networks:
  default:

volumes:
  staticfiles:

services:
  db_recipes:
    <<: *common-app-config
    image: postgres:18.3-alpine3.22@sha256:cd50a785da60925f8f6b59fdf680ae0a10dc96392d5bda489af12d945986dd78
    volumes:
      - $DATADIR/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    <<: *common-app-config
    image: vabene1111/recipes:2.6.9@sha256:969c5b3552ffbf18a6f82b3ad5babbae89bfbd30ab6e3195fd3c158bcf3062ed
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - $DATADIR/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    ports:
      - 127.0.0.1:8255:80
    networks:
      - default
