x-common-app-config: &common-app-config
  restart: unless-stopped

networks:
  default:

volumes:
  staticfiles:

services:
  db_recipes:
    <<: *common-app-config
    image: postgres:18.3-alpine3.22@sha256:af27ebd3413839ccfdcdf88e91ca76ad82117e52192067b76de9bb5be7ea6e04
    volumes:
      - $DATADIR/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    <<: *common-app-config
    image: vabene1111/recipes:2.6.9@sha256:969c5b3552ffbf18a6f82b3ad5babbae89bfbd30ab6e3195fd3c158bcf3062ed
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - $DATADIR/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    ports:
      - 127.0.0.1:8255:80
    networks:
      - default
