x-common-app-config: &common-app-config
  restart: unless-stopped
  environment:
    TZ: $TZ
    TIME_ZONE: $TZ

networks:
  default:
    driver: bridge

########################### SERVICES
services:
  homeassistant:
    <<: *common-app-config
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.6.4@sha256:adb3341e31e03e0048e60d8c1cf952e118a381ae258bb921d3da12a3b27bf0c2
    network_mode: host
    volumes:
      - $DATADIR/homeassistant:/config

  music-assistant-server:
    <<: *common-app-config
    image: ghcr.io/music-assistant/server:2.9.4@sha256:e5dbb44e9dc92ff95dd2b15a9176b238f4e0969aed89850bf428b3d424640ca3
    container_name: music-assistant-server
    network_mode: host
    volumes:
      - '$DATADIR/music-assistant/data:/data'
      - '$DATADIR/music-assistant/media:/media'
      - '$DATADIR/music-assistant/cache:/cache'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined

  zigbee2mqtt:
    <<: *common-app-config
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.12.0@sha256:1debff565ab6841417bd9f7ce8ad44f8c5f25a8b02a24ce3fd79e4779a4763a5
    network_mode: host
    volumes:
      - '$DATADIR/zigbee2mqtt/data:/app/data'
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
    group_add:
      - keep-groups

  zwavejs2mqtt:
    <<: *common-app-config
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:11.19.1@sha256:df776db26a5912eb3223f275ba7e29a76f71aed7c0c2d4316774ae572333b1b5
    network_mode: host
    volumes:
      - '$DATADIR/zwavejs2mqtt/store:/usr/src/app/store'
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0
    group_add:
      - keep-groups
    tty: true
    stop_signal: SIGINT
