networks:
  default:
    driver: bridge

services:
  bds:
    container_name: minecraft_bedrock
    image: itzg/minecraft-bedrock-server@sha256:a1f527cbd8db7ee9b825eb8cfe84ff64d588a91d96cd9d0c1d90196b1d8996e3
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      EULA: 'TRUE'
    ports:
      - '19132:19132/udp'
    volumes:
      - '$DATADIR/minecraft-bedrock/data:/data'
    stdin_open: true
    tty: true
