networks:
  default:
    driver: bridge

services:
  bds:
    container_name: minecraft_bedrock
    image: itzg/minecraft-bedrock-server@sha256:389f2e3a0f781762e7ae6f6fbdd0c5899aa20e2849f04f3daae588c6e5de9fee
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      EULA: 'TRUE'
    ports:
      - '19132:19132/udp'
    volumes:
      - '$DATADIR/minecraft-bedrock/data:/data'
    stdin_open: true
    tty: true
